Dev backend advocate bis
pucardotorg/dristi pull request #207
Opened 2024-05-07 08:04 UTC by manimaarans

2024-05-07 11:45 UTC, atulgupta2024 requested changes
comments added to the code files. please fix

2024-05-10 11:22 UTC, subhashini-egov requested changes
Have suggested changes. Please review @manimaarans

2024-05-10 11:22 UTC, subhashini-egov commented on backend/advocate/src/main/java/org/pucar/util/MdmsUtil.java
How is this service class from the MDMSService?Would it make sense to consolidate?

2024-05-10 12:35 UTC, nileshkgbeehyv commented on backend/advocate/pom.xml
> +            <artifactId>health-services-common</artifactId>
yes

2024-05-17 16:45 UTC, atulgupta2024 approved these changes
there are changes requested in the earlier reviews that are not completed. I am allowing the PR to pass thro' to unblock the team to move forward, but we need to revisit these and fix them later.

2024-05-17 16:46 UTC, atulgupta2024 approved these changes
there are changes requested in the earlier reviews that are not completed. I am allowing the PR to pass thro' to unblock the team to move forward, but we need to revisit these and fix them later.

2024-05-17 16:47 UTC, merged